version: '3.1'
services:
  rabbitmq-container:
    image: rabbitmq:3.11-management
    hostname: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - judge
  
  # callback-queue:
  #   image: rabbit  

  sender-container:
    image: judge-server
    ports:
      - 8081:8081
    environment:
      - spring_rabbitmq_host=rabbitmq-container
    depends_on:
      - rabbitmq-container
    networks:
      - judge

  consumer-container-1:
    image: judge-worker
    ports:
      - 8080:8080
    environment:
      - spring_rabbitmq_host=rabbitmq-container
    depends_on:
      - rabbitmq-container
    networks:
      - judge
  
  consumer-container-2:
    image: judge-worker
    ports:
      - 8082:8080
    environment:
      - spring_rabbitmq_host=rabbitmq-container
    depends_on:
      - rabbitmq-container
    networks:
      - judge

networks:
  judge: