apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  # base64 encode of 'amqp://guest:guest@rabbitmq-keda-cluster.default.svc.cluster.local:5672'
  host: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg==
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
spec:
  scaleTargetRef:
    name: judge-consumer
  pollingInterval: 3 # Optional. Default: 30 seconds
  cooldownPeriod: 10 # Optional. Default: 300 seconds
  maxReplicaCount: 20 # Optional. Default: 100
  minReplicaCount: 1
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: "judge.rpc.requests"
        queueLength: '5'
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn