apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-consumer
spec:
  selector:
    matchLabels:
      app: judge-consumer
  template:
    metadata:
      labels:
        app: judge-consumer
    spec:
      containers:
      - name: judge-consumer
        image: qubejudge/worker
        imagePullPolicy: Never
        env:
        - name: spring_rabbitmq_host
          value: rabbitmq
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
