name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for consumer - arm64
      run: docker buildx --platform=darwin . --file ./consumer/Dockerfile --tag qubejudge-consumer:arm64
    - name: Build the Docker image for consumer - amd64 
      run: docker build . --file ./consumer/Dockerfile --tag qubejudge-consumer:amd64
    - name: Build the Docker image for sender - arm64
      run: docker build --platform=darwin . --file ./sender/Dockerfile --tag qubejudge-sender:arm64
    - name: Build the Docker image for sender - amd64 
      run: docker build . --file ./sender/Dockerfile --tag qubejudge-sender:amd64
