# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build sender with Maven
      run: mvn clean install --file ./sender/pom.xml
    - name: Build consumer with Maven
      run: mvn clean install --file ./consumer/pom.xml
    - run: ls consumer
    - uses: actions/upload-artifact@master
      with:
        name: consumer-0.0.1-SNAPSHOT.jar
        path: consumer/target/consumer-0.0.1-SNAPSHOT.jar
    - uses: actions/upload-artifact@master
      with:
        name: sender-0.0.1-SNAPSHOT.jar
        path: sender/target/sender-0.0.1-SNAPSHOT.jar
    
#   publish-job:
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#           cache: maven
#       - run: ls consumer
#       - run: ls
#       - run: mkdir consumer/staging && cp consumer/target/*.jar consumer/staging
#       - uses: actions/upload-artifact@v1
#         with:
#           name: Package
#           path: staging
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: actions/download-artifact@master
      with: 
        name: consumer-0.0.1-SNAPSHOT.jar
        path: consumer/target/consumer-0.0.1-SNAPSHOT.jar
    - uses: actions/download-artifact@master
      with: 
        name: sender-0.0.1-SNAPSHOT.jar
        path: sender/target/sender-0.0.1-SNAPSHOT.jar
    - run: ls consumer
    - run: ls sender
    - run: cd consumer
    - name: Build the Docker image for consumer - amd64 
      run: docker build . --file ./consumer/Dockerfile --tag qubejudge-consumer:amd64
# #       - name: Build the Docker image for sender - arm64
# #         run: docker buildx build --platform=darwin . --file ./sender/Dockerfile --tag qubejudge-sender:arm64
    - run: cd ../sender
    - name: Build the Docker image for sender - amd64 
      run: docker build . --file ./sender/Dockerfile --tag qubejudge-sender:amd64

# #     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
# # #     - name: Update dependency graph
# # #       uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
